# Generated by Django 4.2.11 on 2024-03-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localwithdrawal',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_withdrawals', to='appusers.pin'),
        ),
    ]
