# Generated by Django 4.2.11 on 2024-03-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0002_alter_localwithdrawal_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localwithdrawal',
            name='pin',
        ),
    ]
