# Generated by Django 4.2.11 on 2024-03-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0005_rename_time_transactionhistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
