# Generated by Django 4.2.11 on 2024-03-30 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0006_alter_transactionhistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='reference_number',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
